name: Compile release general kernel

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Initialization environment
        id: init
        run: |
          sudo -E apt-get -y update
          sudo -E apt-get -y install gcc make gettext bison flex bc zlib1g-dev libncurses5-dev lzma
          echo "status=success" >> ${GITHUB_OUTPUT}
      - name: make build
        id: build
        working-directory: /builder
        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
        run: |
          mkdir -p /builder
          git clone -q --single-branch --depth=1 --branch=v2.x https://github.com/cndeep/HiSTBLinuxV100R005C00SPC050 mv310
          cd mv310
          cp configs/hi3798mv310/hi3798mv31dmg_hi3798mv310_cfg.mak ./cfg.mak
          source ./env.sh
          make build -j4 2>&1  | tee -a buildlog.txt
          ls -R /builder/out/hi3798mv310
          cho "status=success" >> ${GITHUB_OUTPUT}
